package br.ufes.inf.lprm.scene.examples.connectionswitch;


import br.ufes.inf.lprm.situation.*;
import br.ufes.inf.lprm.scene.base.*;
import br.ufes.inf.lprm.scene.base.evaluators.*;
import br.ufes.inf.lprm.scene.examples.shared.*
import br.ufes.inf.lprm.scene.util.SituationHelper;

rule "SituationConnected"
@role(situation)
@type(SituationConnected)
@snapshot(on)
@restore(first)
salience 10
    when
    	device: Device(network: this.connection, this.connection != null)
    then
    	SituationHelper.situationDetected(drools);
end

rule "SituationSwitch"
@role(situation)
@type(SituationSwitch)
	when
		wlan: 		SituationConnected(	$device: device, 
										device.connection != null, 
										device.connection.type == NetworkType.WLAN)
		bluetooth: 	SituationConnected(	device.id == $device.id, 
										device.connection != null, 
										device.connection.type == NetworkType.BLUETOOTH, 
										this after wlan)
	then
		SituationHelper.situationDetected(drools);
end