package br.ufes.inf.lprm.scene.base.evaluators;

import br.ufes.inf.lprm.scene.base.*;
import br.ufes.inf.lprm.scene.base.evaluators.AfterEvaluatorTest.*;

rule "Fever"
@role(situation)
@type(Fever)
    when
    	febrile: Person(this.temperature > 37)
    then
    	System.out.println("xxxx");
    	SituationHelper.situationDetected(drools);
end

rule "FeverAfterFever"
@role(situation)
@type(FeverAfterFever)
    when
    	previous: Fever($f1: febrile)
    	latter: Fever(febrile==$f1, this after previous)
    then
    	System.out.println("aaaa");
    	SituationHelper.situationDetected(drools);
end