package br.ufes.inf.lprm.scene.examples.fever;

import br.ufes.inf.lprm.scene.base.*;
import br.ufes.inf.lprm.situation.Situation;

declare Person
    identifier: Integer
    name: String
    temperature: Integer
end

declare Fever extends Situation
    febrile: Person
end

rule "FeverSituation"
@role(situation)
@type(Fever)
    when
    	f1: Person(temperature > 37)
    then
    	SituationHelper.situationDetected(drools);
end
