package br.ufes.inf.lprm.scene.examples.fever;

import br.ufes.inf.lprm.scene.base.*;
import br.ufes.inf.lprm.situation.*;

declare Person
	identifier: int
	name: String
	temperature: int
end

declare Fever extends SituationType
    febrile: Person @part(label = "f1")
end

rule "FeverSituation"
@role(situation)
@type(Fever)
    when
    	f1: Person(temperature > 37)
    then
    	SituationHelper.situationDetected(drools);
end
