package br.ufes.inf.lprm.scene;

import java.util.ArrayList;
import java.util.HashMap;
dialect  "mvel"

declare Plate
    id: Integer;
    name: String;
end;

declare Car
    id: Integer;
    name: String;
end;

declare Person
    id: Integer;
    name: String;
    temperature: Float;
    cars: ArrayList @type(Car);
end;

rule "Fever"
    when
        $p: Person(temperature > 37);
    then
        System.out.println($p + " is running a fever.");
end;

rule "Person has car"
    when
        $c: Car(name == "Higor's Car");
        $p: Person(cars contains $c);
    then
    System.out.println($p + " has " + $c);
end;

