package scene

import br.ufes.inf.lprm.scene.model.impl.Situation;
import br.ufes.inf.lprm.scene.util.SituationHelper;
import br.ufes.inf.lprm.situation.annotations.part;
declare Person
    name: String
    temperature: int
end

declare Fever extends Situation
    febrile: Person @part(label = "f1")
end

rule "FeverSituation"
@role(situation)
@type(Fever)
    when
    	f1: Person(temperature > 37)
    then
    	SituationHelper.situationDetected(drools);
end

rule "WhenFever"
    when
    	$sit: Situation()
    then
    	System.out.println($sit);
end